#import sys.inputs.lib as bnp


#set text(font: "Noto Sans Symbols 2")


#bnp.chess-sym.pawn.filled
#bnp.chess-sym.pawn.filled.r
#bnp.chess-sym.pawn.filled.b
#bnp.chess-sym.pawn.filled.l
#bnp.chess-sym.pawn.stroked
#bnp.chess-sym.pawn.stroked.r
#bnp.chess-sym.pawn.stroked.b
#bnp.chess-sym.pawn.stroked.l
#bnp.chess-sym.pawn.white
#bnp.chess-sym.pawn.white.r
#bnp.chess-sym.pawn.white.b
#bnp.chess-sym.pawn.white.l
#bnp.chess-sym.pawn.black
#bnp.chess-sym.pawn.black.r
#bnp.chess-sym.pawn.black.b
#bnp.chess-sym.pawn.black.l
#bnp.chess-sym.pawn.neutral
#bnp.chess-sym.pawn.neutral.r
#bnp.chess-sym.pawn.neutral.b
#bnp.chess-sym.pawn.neutral.l

#bnp.chess-sym.knight.filled
#bnp.chess-sym.knight.filled.r
#bnp.chess-sym.knight.filled.b
#bnp.chess-sym.knight.filled.l
#bnp.chess-sym.knight.stroked
#bnp.chess-sym.knight.stroked.r
#bnp.chess-sym.knight.stroked.b
#bnp.chess-sym.knight.stroked.l
#bnp.chess-sym.knight.white
#bnp.chess-sym.knight.white.r
#bnp.chess-sym.knight.white.b
#bnp.chess-sym.knight.white.l
#bnp.chess-sym.knight.black
#bnp.chess-sym.knight.black.r
#bnp.chess-sym.knight.black.b
#bnp.chess-sym.knight.black.l
#bnp.chess-sym.knight.neutral
#bnp.chess-sym.knight.neutral.r
#bnp.chess-sym.knight.neutral.b
#bnp.chess-sym.knight.neutral.l

#bnp.chess-sym.bishop.filled
#bnp.chess-sym.bishop.filled.r
#bnp.chess-sym.bishop.filled.b
#bnp.chess-sym.bishop.filled.l
#bnp.chess-sym.bishop.stroked
#bnp.chess-sym.bishop.stroked.r
#bnp.chess-sym.bishop.stroked.b
#bnp.chess-sym.bishop.stroked.l
#bnp.chess-sym.bishop.white
#bnp.chess-sym.bishop.white.r
#bnp.chess-sym.bishop.white.b
#bnp.chess-sym.bishop.white.l
#bnp.chess-sym.bishop.black
#bnp.chess-sym.bishop.black.r
#bnp.chess-sym.bishop.black.b
#bnp.chess-sym.bishop.black.l
#bnp.chess-sym.bishop.neutral
#bnp.chess-sym.bishop.neutral.r
#bnp.chess-sym.bishop.neutral.b
#bnp.chess-sym.bishop.neutral.l

#bnp.chess-sym.rook.filled
#bnp.chess-sym.rook.filled.r
#bnp.chess-sym.rook.filled.b
#bnp.chess-sym.rook.filled.l
#bnp.chess-sym.rook.stroked
#bnp.chess-sym.rook.stroked.r
#bnp.chess-sym.rook.stroked.b
#bnp.chess-sym.rook.stroked.l
#bnp.chess-sym.rook.white
#bnp.chess-sym.rook.white.r
#bnp.chess-sym.rook.white.b
#bnp.chess-sym.rook.white.l
#bnp.chess-sym.rook.black
#bnp.chess-sym.rook.black.r
#bnp.chess-sym.rook.black.b
#bnp.chess-sym.rook.black.l
#bnp.chess-sym.rook.neutral
#bnp.chess-sym.rook.neutral.r
#bnp.chess-sym.rook.neutral.b
#bnp.chess-sym.rook.neutral.l

#bnp.chess-sym.queen.filled
#bnp.chess-sym.queen.filled.r
#bnp.chess-sym.queen.filled.b
#bnp.chess-sym.queen.filled.l
#bnp.chess-sym.queen.stroked
#bnp.chess-sym.queen.stroked.r
#bnp.chess-sym.queen.stroked.b
#bnp.chess-sym.queen.stroked.l
#bnp.chess-sym.queen.white
#bnp.chess-sym.queen.white.r
#bnp.chess-sym.queen.white.b
#bnp.chess-sym.queen.white.l
#bnp.chess-sym.queen.black
#bnp.chess-sym.queen.black.r
#bnp.chess-sym.queen.black.b
#bnp.chess-sym.queen.black.l
#bnp.chess-sym.queen.neutral
#bnp.chess-sym.queen.neutral.r
#bnp.chess-sym.queen.neutral.b
#bnp.chess-sym.queen.neutral.l

#bnp.chess-sym.king.filled
#bnp.chess-sym.king.filled.r
#bnp.chess-sym.king.filled.b
#bnp.chess-sym.king.filled.l
#bnp.chess-sym.king.stroked
#bnp.chess-sym.king.stroked.r
#bnp.chess-sym.king.stroked.b
#bnp.chess-sym.king.stroked.l
#bnp.chess-sym.king.white
#bnp.chess-sym.king.white.r
#bnp.chess-sym.king.white.b
#bnp.chess-sym.king.white.l
#bnp.chess-sym.king.black
#bnp.chess-sym.king.black.r
#bnp.chess-sym.king.black.b
#bnp.chess-sym.king.black.l
#bnp.chess-sym.king.neutral
#bnp.chess-sym.king.neutral.r
#bnp.chess-sym.king.neutral.b
#bnp.chess-sym.king.neutral.l

#bnp.chess-sym.knight.filled.tr
#bnp.chess-sym.knight.filled.br
#bnp.chess-sym.knight.filled.bl
#bnp.chess-sym.knight.filled.tl
#bnp.chess-sym.knight.stroked.tr
#bnp.chess-sym.knight.stroked.br
#bnp.chess-sym.knight.stroked.bl
#bnp.chess-sym.knight.stroked.tl
#bnp.chess-sym.knight.white.tr
#bnp.chess-sym.knight.white.br
#bnp.chess-sym.knight.white.bl
#bnp.chess-sym.knight.white.tl
#bnp.chess-sym.knight.black.tr
#bnp.chess-sym.knight.black.br
#bnp.chess-sym.knight.black.bl
#bnp.chess-sym.knight.black.tl
#bnp.chess-sym.knight.neutral.tr
#bnp.chess-sym.knight.neutral.br
#bnp.chess-sym.knight.neutral.bl
#bnp.chess-sym.knight.neutral.tl

#bnp.chess-sym.knight.bishop.filled
#bnp.chess-sym.knight.bishop.stroked
#bnp.chess-sym.knight.bishop.white
#bnp.chess-sym.knight.bishop.black
#bnp.chess-sym.knight.rook.filled
#bnp.chess-sym.knight.rook.stroked
#bnp.chess-sym.knight.rook.white
#bnp.chess-sym.knight.rook.black
#bnp.chess-sym.knight.queen.filled
#bnp.chess-sym.knight.queen.stroked
#bnp.chess-sym.knight.queen.white
#bnp.chess-sym.knight.queen.black

#bnp.chess-sym.equihopper.filled
#bnp.chess-sym.equihopper.filled.rot
#bnp.chess-sym.equihopper.stroked
#bnp.chess-sym.equihopper.stroked.rot
#bnp.chess-sym.equihopper.white
#bnp.chess-sym.equihopper.white.rot
#bnp.chess-sym.equihopper.black
#bnp.chess-sym.equihopper.black.rot
#bnp.chess-sym.equihopper.neutral
#bnp.chess-sym.equihopper.neutral.rot

#bnp.chess-sym.soldier.filled
#bnp.chess-sym.soldier.stroked
#bnp.chess-sym.soldier.red
#bnp.chess-sym.soldier.black
#bnp.chess-sym.cannon.filled
#bnp.chess-sym.cannon.stroked
#bnp.chess-sym.cannon.red
#bnp.chess-sym.cannon.black
#bnp.chess-sym.chariot.filled
#bnp.chess-sym.chariot.stroked
#bnp.chess-sym.chariot.red
#bnp.chess-sym.chariot.black
#bnp.chess-sym.horse.filled
#bnp.chess-sym.horse.stroked
#bnp.chess-sym.horse.red
#bnp.chess-sym.horse.black
#bnp.chess-sym.elephant.filled
#bnp.chess-sym.elephant.stroked
#bnp.chess-sym.elephant.red
#bnp.chess-sym.elephant.black
#bnp.chess-sym.mandarin.filled
#bnp.chess-sym.mandarin.stroked
#bnp.chess-sym.mandarin.red
#bnp.chess-sym.mandarin.black
#bnp.chess-sym.general.filled
#bnp.chess-sym.general.stroked
#bnp.chess-sym.general.red
#bnp.chess-sym.general.black
